name: tests

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  process_replay:
    name: process replay
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - name: pre-upload sleep
      run: sleep "$(cat .github/ci_pr_sleep 2>/dev/null || echo 0)"
    - name: make diff report
      if: github.event_name == 'pull_request'
      run: |
        echo "diff report for sha ${{ github.event.pull_request.head.sha }} run ${{ github.run_id }}" > diff_report.txt
    - name: Upload diff report
      uses: actions/upload-artifact@v4
      if: always() && github.event_name == 'pull_request'
      continue-on-error: true
      with:
        name: diff_report_${{ github.event.number }}
        path: diff_report.txt
  slow:
    name: slow job
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - name: sleep
      run: sleep "$(cat .github/ci_sleep 2>/dev/null || echo 60)"
