name: tests
on:
  pull_request:
    branches: [repro-diff-report-base]
jobs:
  process_replay:
    name: process replay
    runs-on: [self-hosted, linux, X64]
    steps:
      - uses: actions/checkout@v4
      - name: simulate tests
        run: sleep 240
      - name: produce diff report
        run: echo "diff_report for SHA ${{ github.event.pull_request.head.sha }}" > diff_report.txt
      - uses: actions/upload-artifact@v4
        with:
          name: diff_report_${{ github.event.number }}
          path: diff_report.txt
